call plug#begin('~/.vim/plugged')
Plug 'junegunn/seoul256.vim'
Plug 'tpope/vim-surround'
Plug 'joshdick/onedark.vim'
Plug 'sheerun/vim-polyglot'
Plug 'dense-analysis/ale'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-repeat'
call plug#end()

"indentation
set history=200 
set shiftwidth=4 softtabstop=4 expandtab 
set autoindent 
set smartindent 
set shiftround

"search options
set smartcase
set incsearch
set hlsearch

"mouse
set mouse=a

"gutter always open
set signcolumn=yes

" Set the title of the Terminal to the currently open file
function! SetTerminalTitle()
    let titleString = expand('%:t')
    if len(titleString) > 0
        let &titlestring = expand('%:t')
        " this is the format iTerm2 expects when setting the window title
        let args = "\033];".&titlestring."\007"
        let cmd = 'silent !echo -e "'.args.'"'
        execute cmd
        redraw!
    endif
endfunction

autocmd BufEnter * call SetTerminalTitle()

"syntax highlighting
"colorscheme elflord
let g:seoul256_background = 234
colo seoul256
" colorscheme onedark

let g:ale_linters = {
    \   'python': ['flake8', 'pylint']
    \}

"relative line numbers
set number
"set relativenumber
set numberwidth=4

"show matching bracket
"set showmatch

"set leader
let mapleader = ","

"set localleader
let maplocalleader = "\\"

"NORMAL MODE REMAPS
"add quotes
nnoremap <leader>" viw<esc>a"<esc>bi"<esc>lel
nnoremap <leader>' viw<esc>a'<esc>bi'<esc>lel
vnoremap <leader>" <esc>a"<esc>`<i"<esc>`>2l
vnoremap <leader>' <esc>a'<esc>`<i'<esc>`>2l

"move to beginning, end of line
nnoremap H ^
nnoremap L $

"remap original H, L
nnoremap <leader>H H
nnoremap <leader>L L

"remap , function
nnoremap <leader>, ,

"allow return to clear search highlighting
nnoremap <CR> :noh<CR><CR>

"new blank line under current line
nnoremap <leader>n o<esc>

"new blank line above current line
nnoremap <leader>N O<esc>

"vimrc
nnoremap <leader>ev :split $MYVIMRC<cr>
nnoremap <leader>eg :split $MYGVIMRC<cr>
nnoremap <leader>sv :source $MYVIMRC<cr>
nnoremap <leader>sg :source $MYVIMRC<cr>:source $MYGVIMRC<cr>:source $MYGVIMRC<cr>

"move line down
nnoremap <leader>- ddp

"move line up (doesn't work for last line of file)
nnoremap <leader>_ ddkP

"word to upper
nnoremap <leader><c-u> viwU

" insert at correct tab position
nnoremap <leader>i ko

"INSERT MODE REMAPS
"set escape to jk
inoremap jk <ESC>
"inoremap [ []<Left>
"inoremap ( ()<Left>
"inoremap " ""<Left>
"inoremap ' ''<Left>

" add matching curly bracket

"word to upper (adds weird space)
inoremap <leader><c-u> <esc>viwUea 


"ABBREVIATIONS 
iabbrev { {<esc>o}<esc>kA

"TERMINAL
tnoremap jk <C-\><C-n>
tnoremap <esc> <C-\><C-n>
nnoremap <leader>T :below term<cr><C-\><C-n>:resize 20<cr>
let &shell='/bin/bash --login'

"typos
iabbrev waht what
iabbrev tehn then
iabbrev hellow hello

"info
iabbrev bm Barry Molina
iabbrev baz bazzboy@gmail.com

"java
augroup FileType_java
    autocmd!
    autocmd filetype java iabbrev <buffer> print System.out.print("");<left><left><left>
    autocmd filetype java iabbrev <buffer> printf System.out.printf("");<left><left><left>
    autocmd filetype java iabbrev <buffer> sout System.out.println("");<left><left><left>
    autocmd filetype java iabbrev <buffer> fori for (int i = 0; i < arr.length; i++) {<cr>}<esc>kfaciw
    autocmd filetype java iabbrev <buffer> func public void functionName() {<cr>}<esc>ko
    autocmd filetype java iabbrev <buffer> scan import java.util.Scanner;
    autocmd filetype java iabbrev <buffer> key Scanner keyboard = new Scanner(System.in);
    autocmd FileType java setlocal norelativenumber
    autocmd FileType java setlocal nowrap
    autocmd FileType java nnoremap <buffer> <localleader>c I// <esc>
    autocmd FileType java vnoremap <buffer> <localleader>c <esc>`<<C-v>`>I// <esc>
augroup END

"AUTOCOMMANDS 
augroup filetype_html
    autocmd!
    autocmd FileType html setlocal nowrap
    autocmd FileType html setlocal spell
    autocmd FileType html vnoremap <buffer> <localleader>c <esc>`<I<!-- <esc>`>A --><esc>
    autocmd FileType html vnoremap <buffer> <localleader>dc <esc>`<^daw`>daw
    autocmd FileType html iabbrev <buffer> <localleader>l" &ldquo;
    autocmd FileType html iabbrev <buffer> <localleader>r" &rdquo;
augroup END

augroup FileType_css
    autocmd!
    autocmd FileType css vnoremap <buffer> <localleader>c <esc>`<I/* <esc>`>A */<esc>
    autocmd FileType css vnoremap <buffer> <localleader>dc <esc>`<^daw`>daw
augroup END

augroup FileType_python
    autocmd!
    autocmd FileType python nnoremap <buffer> <localleader>c I# <esc>
    autocmd FileType python vnoremap <buffer> <localleader>c I# <esc>
augroup END

augroup FileType_vim
    autocmd!
    autocmd FileType vim nnoremap <buffer> <localleader>c I"<esc>
    autocmd FileType vim vnoremap <buffer> <localleader>c I"<esc>
augroup END
