call plug#begin('~/.vim/plugged')
"Plug 'junegunn/seoul256.vim'
"Plug 'tpope/vim-surround'
"Plug 'joshdick/onedark.vim'
"Plug 'sheerun/vim-polyglot'
Plug 'dense-analysis/ale'
call plug#end()

let g:ale_sign_column_always = 1
